security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
        # admin:
        #     pattern: ^/admin
        #     logout:
        #         path: admin_logout
        #         target: admin_login
        #     custom_authenticators:
        #         - App\Security\AdminAuthenticator
    # access_control:
    # - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/admin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }