security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
        admin:
            pattern: ^/admin
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: /admin # Redirige après la connexion réussie
            logout:
                path: admin_logout
                target: admin_login
    # access_control:
    # - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/admin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }