vich_uploader:
    db_driver: orm
    mappings:
        concert_images:
            uri_prefix: /images/concerts
            upload_destination: '%kernel.project_dir%/public/images/concerts'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        pass_images:
            uri_prefix: /images/passes
            upload_destination: '%kernel.project_dir%/public/images/passes'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        location_files:
            uri_prefix: /images/location
            upload_destination: '%kernel.project_dir%/public/images/location'
            namer: Vich\UploaderBundle\Naming\OrignameNamer