vich_uploader:
    db_driver: orm
    mappings:
        concert_images:
            uri_prefix: /images/concerts
            upload_destination: '%kernel.project_dir%/public/images/concerts'
            namer: Vich\UploaderBundle\Naming\OrignameNamer 