controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

api_concerts:
    path: /api/concerts
    controller: App\Controller\ConcertApiController::getConcerts
    methods: GET

api_passes:
    path: /api/passes
    controller: App\Controller\PassApiController::getPasses
    methods: GET    